tighten/jigsaw

- site/.gitignore
- site/config.php
- site/gulpfile.js
- site/package.json
- site/source/_layouts/master.blade.php
- site/source/index.blade.php
- src/Console/InitCommand.php
Still a work in progress, but currently:
- Scaffolds default `package.json`
- Scaffolds default `gulpfile.json`
- Scaffolds default `.gitignore`
- Scaffolds basic master layout and index template
- Scaffolds empty `main.scss` (and `main.css` so fresh sites have no console errors)
- `gulp watch` watches for all changes in the `source` folder and recompiles the site if anything changes
Nice to haves:
- ~~Currently updating an asset file (like `main.scss`) triggers two recompiles because the Sass file changes, which triggers the CSS file to change. It would be nice to avoid this, but it might only be possible by moving precompiled assets out of the `source` folder.~~
- It would be kind of nice to not compile assets into the `source` folder, and instead only compile them into the `build` …
> Scaffold Laravel Elixir integration when initializing new sites

- site/gulpfile.js
This adds browsersync to the gulpfile for live reloading and cross device testing.
Has the added side bonus of not really having to worry about writing our own `jigsaw serve` command or anything, `gulp watch` does all of it now.
> Add BrowserSync to gulpfile

- composer.json
- jigsaw
- phpunit.xml
- src/Handlers/BladeHandler.php
- src/Handlers/MarkdownHandler.php
- src/TemporaryFilesystem.php
Allows you to create files  with `.markdown` or `.md` extensions that will be compiled to HTML.
Specifying which layout to use and the layout section is done through YAML front matter. For example, you might have a layout like this:
```html
<html>
<head>...</head>
<body>
@yield('body')
</body>
</html>
```
If that layout was named `master` in the `_layouts` folder, you could create a Markdown template that used this layout like so:
```markdown
---
extends: _layouts.master
section: body
---
My awesome content!
```
There is also support for custom front matter variables, so given a template like:
```html
<html>
<head>...</head>
<body>
@yield('body')
@if (isset($footer))
<footer>{{ $footer }}</footer>
@endif
</body>
</html>
```
...and a Markdown file like this:
```markdown
---
extends: …
```
> Add basic support for Markdown

- src/Handlers/MarkdownHandler.php
This resolves #21 by injecting the Markdown content as a variable to be echo'd by the template, rather than compiling it flat into the template as we were before.
> Inject markdown content as variable instead of rendering flat into Blade template, resolves #21

- site/gulpfile.js
`jigsaw build` wasn't run when files in the root of the source directory were being changed. This adjustment also makes the `exec` command watch for changes to the root files.
> Run jigsaw build on changed root files

- composer.json
> Update symfony/console dependency to use "^2.5|^3.0"

- site/gulpfile.js
- site/package.json
This will trigger the `jigsaw build` with the correct environment variable and also the browserSync to serve from the correct source dir.
> Add optional --env or -e parameter to gulp watch

- readme.md
- src/Console/BuildCommand.php
Hello, 
This changes build commands environment from an option to an argument. 
`$ jigsaw build --env=production ` would not be `$ jigsaw build production`. 
This is consistent with the serve command as discussed in PR#31.
Thanks
> Change env in build command from option to argument

- site/gulpfile.js
- site/package.json
As requested I'm re-opening this pull request.
This is a simple change to the Gulp/BrowserSync configuration to facilitate building of all jigsaw sites not just the local one.
There may be circumstances where a user wants to work on any one of the variants of a Jigsaw site during development. For example;
- Configuration in `config.<site>.php ` can effect how the site operates. The local site might use placeholder content but the production site uses ajax to pull in content.
- A Jigsaw site might be a template with `config.client-site-1.php` and `config.client-site-2.php` etc.  determing what content to pull in allowing one Jigsaw site to be reused for multiple paying clients (this is my use case).
- Maybe there are different localisations in `config.en_GB.php ` and `config.en_US.php `. …
> Allow Browsersync to build all sites not just the local one.

- site/gulpfile.js
Defaults to the default Browser Sync port: 3000.
> Allow Browser Sync port to be specified from command line

- composer.json
- src/Support/helpers.php
Hey Adam,
As mentioned in #51 I was able to set up versioning for jigsaw so it works the same as it does in Laravel.
I included `src/Support/helpers.php` which contains `public_path()` and `elixir()`. `public_path()` makes sure that it uses the `rev-manifest.json` within the source folder. And I included it all in the files section of `composer.json` for autoloading.
I also noticed that it included a duplicate slash if an empty build path was used (which is necessary when using relative paths to fonts or images from css), so I included a check to handle that.
> Add Elixir versioning

- jigsaw
- site/bootstrap.php
Referencing issue #64.
Placing a `bootstrap.php` file on the root of your jigsaw will load it before registering all file handlers.
The markdown and yaml parsers are resolved using the service container so you can re-bind them and extend parsedown.
Files to make the [inline colored text](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions) in the parsedown wiki.
```php
<?php
// File: /bootstrap.php
use App\UberParsedown;
use Mni\FrontYAML\Markdown\MarkdownParser;
/** @var $container \Illuminate\Container\Container */
/** @var $jigsaw \TightenCo\Jigsaw\Jigsaw */
$container->bind(MarkdownParser::class, UberParsedown::class);
```
```php
<?php
// File: /app/UberParsedown.php
namespace App;
use Mni\FrontYAML\Markdown\MarkdownParser;
use Parsedown;
class UberParsedown extends …
```
> Customizing Parsedown

- site/gulpfile.js
- site/package.json
- site/tasks/bin.js
When running gulp, instead of making the user change the gulp file, manually,
add a check for which jigsaw binary to use (global or local under vendor
folder) and in the case none exists prints a message to stdout via
console.log and exits the process.
> Allow gulp command to check which jigsaw binary to use

- jigsaw
- src/BladeDirectivesFile.php
- src/BladeFile.php
See #67.
To register a blade directive:
```php
<php
// blade.php
return [
'datetime' => function ($expression) {
return '<?php echo date("Y-m-d H:i:s", ' . $expression . '); ?>';
}
];
```
I didn't add the $page parameter because it was calculated using get_defined_vars() on the resolved blade instance.
> Add ability to register custom blade tags

- src/PathResolvers/PrettyOutputPathResolver.php
When I tried to publish my Jigsaw site with Github Pages, I noticed that `jigsaw build production` copied the `CNAME` file over incorrectly from `source/` with a trailing `.` character.
I added a check for an empty `$type` and returns the path without the `.` in the file.
> Copy files without an extension properly

- src/Collection/CollectionPaginator.php
Safety check before rtrim() call in order to support pagination on source/index.blade.php
When using pagination on the home page `source/index.blade.php`, the call to `$pagination->previous` when on the _second_ page returns `null`.
I believe the issue lies withing `TightenCo\Jigsaw\Collection\ CollectionPaginator:: getPageLink()` that performs a `return rtrim($this->outputPathResolver->link(...), '/');`
> Fix pagination bug on home page

- src/PathResolvers/PrettyOutputPathResolver.php
Resolve issue with PrettyOutputPathResolver not trimming paths correctly in Windows
#131
> Make all trims of paths/urls Windows friendly

- site/tasks/bin.js
- src/File/InputFile.php
@damiani when runnign on Windows 10, I found running the local jigsaw from the vendor directory would crap out:
```
'.' is not recognized as an internal or external command,
operable program or batch file.
```
I implemented these changes as I was debugging and reusing the pull request here: https://github.com/tightenco/jigsaw/pull/126, which i needed in order to proceed with my development.
Thanks for your work here!
Adam
> Normalize the local jigsaw path call for Windows

- src/Handlers/PaginatedPageHandler.php
This option allows the user to control the pagination globally on site.
Avoiding the default 10 items per page.
> Pagination per page default option on config file

- src/View/ViewRenderer.php
I use `.atom` files instead of `.rss`. Don't ask me why, but that's where my feed has been for ages, so I figured I'd try it out. :)
> Allow .atom files

- src/Collection/Collection.php
- tests/config.php
- tests/snapshots/sort-test-multi/index.html
- tests/source/_sort_tests/sort-test-1-C.md
- tests/source/_sort_tests/sort-test-1-a.md
- tests/source/_sort_tests/sort-test-1-b.md
- tests/source/_sort_tests/sort-test-1-d.md
- tests/source/_sort_tests/sort-test-2-B.md
- tests/source/_sort_tests/sort-test-2-a.md
- tests/source/_sort_tests/sort-test-2-c.md
- tests/source/_sort_tests/sort-test-3-e.md
- tests/source/_sort_tests/sort-test-3-f.md
- tests/source/sort-test-multi.blade.php
Fixes https://github.com/tightenco/jigsaw/issues/154
When working with collections, the `sort` parameter in `config.php` can accept an array of multiple values. This was previously done with chained calls to the Illuminate/Collection `sortBy` or `sortByDesc` methods, but that doesn't do what we expect; instead (as referenced in https://github.com/laravel/internals/issues/11), it does not maintain the order of any of the preliminary sorts, and in the end only sorts by the final `sortBy` clause.
This has been fixed by using the `sort` method, which calls PHP's `usort` under the hood and allows us to do our own comparison. I've used what I believe is a pretty elegant solution from https://stackoverflow.com/a/27364612/4043861, which makes the comparison between adjacent items by stepping …
> Fix sorting of collection items by multiple variables

- src/PathResolvers/CollectionPathResolver.php
- tests/config.php
- tests/snapshots/Remove Invalid Characters, from Paths?!/index.html
- tests/source/_invalid_path_characters_test/remove_invalid_characters.md
Resolves https://github.com/tightenco/jigsaw/issues/145#issuecomment-329870894
When specifying a variable to use as a path name (e.g. `title`) and _not_ slugifying it (as with `'path' => '{title}'`), we need to strip out any characters that are not valid in URLs. This was the behavior in v1.0, but was inadvertently changed since then. I'm opting not to use `urlencode` because we want to maintain `/` characters (for nested paths and date processing), nor FILTER_VALIDATE_URL, which would remove spaces. A good old-fashioned regex restores behavior that is consistent with v1.0.
> Strip URL-invalid characters from path names

- src/CollectionItemHandlers/MarkdownCollectionItemHandler.php
- src/Handlers/MarkdownHandler.php
- src/View/ViewRenderer.php
I noticed whenever I try and save a file with markdown or YAML in it, mac computers try to save default as .mdown
I tried to build the application with this file type but was met with an exception
```
[Exception]                          
No matching collection item handler  
```
So I added this file type in as it seems logical that jigsaw should support it.
> Added support for .mdown files, the default for mac computers.

- src/SiteBuilder.php
That feature allows user to set a `permalink` key in the page's YAML front matter.
> 404.blade.md
``` markdown
---
extends: _layouts.master
title: "404 Error"
permalink: 404.html
section: body
---
```
This configuration will change the default output from `404/index.html` to permalink's destination: `404.html`.
> Adding permalink option on page data

- src/File/InputFile.php
- src/SiteBuilder.php
- src/View/ViewRenderer.php
- tests/snapshots/extension-url-test.atom
- tests/source/extension-url-test.blade.atom
This PR fixes an issue where "extra" whitelisted text-type files that can be preprocessed with Blade  (e.g. `.blade.js` or `.blade.atom`) were missing the extra extension (e.g. `.js` or `.atom`) from their `path` and `url` meta values, causing `getPath()` and `getUrl()` to return incorrect path references.
> Set path and url to contain extra (non-html) Blade extensions if present

- composer.json
- jigsaw
This PR adds support for version 5.6 of the Illuminate components, and bumps PHPUnit to 7.0.
> Bump Illuminate versions to 5.6

- composer.json
- src/Collection/CollectionItem.php
- src/File/InputFile.php
- src/Handlers/BladeHandler.php
- src/Handlers/DefaultHandler.php
- src/Support/helpers.php
- tests/CollectionItemTest.php
This PR is inspired by [this question](https://github.com/tightenco/jigsaw/issues/185#issuecomment-368795725), and adds a `__toString` method to `CollectionItem`, to return the contents of a collection item—parsed Markdown, for instance—whenever the item is referenced as a string. 
This would allow referencing a specific Markdown collection item in a Blade template like this:
```blade
@foreach ($notes as $note)
{!! $note !!}
@endforeach
```
...instead of needing to reference `$note->getContent()`.
---
This PR includes some changes to path handling, replacing `realpath` and `getRealPath` which don't play nicely with the virtual file system used in our tests.
---
I'm working simultaneously on addressing the lack of support for `getContent()` in Blade files …
> Reference collection item content as strings

- composer.json
Was experiencing conflicts in a few projects due to other packages using the 1.0.0 package of Mockery. Bumped jigsaw to 1.0.0 and ran the tests. All green! 👍
> bump mockery to ^1.0.0

- src/Jigsaw.php
Fixes https://github.com/tightenco/jigsaw/issues/202
- Replace `forget` with `except` in Jigsaw.php `getCollections` helper
> Fix issue with getCollections in afterCollections or afterBuild event listeners

- jigsaw-core.php
- src/File/BladeDirectivesFile.php
In `blade.php` the `BladeCompiler` is now exposed as `$bladeCompiler`;
An example of registering a component alias:
```php
/** @var \Illuminate\View\Compilers\BladeCompiler $bladeCompiler */
$bladeCompiler->component('_components.title');
// extend more
$bladeCompiler->include(...);
$bladeCompiler->directive(...);
// make sure you still return an array!
return [
// custom directives... 
// Same thing as calling $bladeCompiler->directive(...) above
];
```
```blade
{{--before--}}
@component('_components.title')
Title 1
@endcomponent
{{--after--}}
@title
Title 2
@endtitle
```
> Expose bladeCompiler in blade.php to make extending blade easier and more future-proof

- src/Console/InitCommand.php
Right now, if you run `jigsaw init` on an existing jigsaw project, it will nuke your project by overwriting all the jigsaw files.
This PR should add a confirmation prompt to the command to alert users what they are about to do. It should be conditionally added based on if there is an existing `config.php` already or not.
> Add a confirmation prompt to the "init" command

- stubs/site/source/_layouts/master.blade.php
Since we have Mix out of the box, we can drop the old default `main.css` file, as it's just confusing at this point.
> Drop non-generated CSS file

- src/IterableObject.php
- src/Jigsaw.php
- tests/EventsTest.php
This PR enhances the behavior of the `setConfig()` method in the `beforeBuild` event listener, allowing:
- setting a deeply-nested config value using dot notation, e.g.:
> _bootstrap.php_
```
$events->beforeBuild(function (Jigsaw $jigsaw) {
$jigsaw->setConfig('deeply.nested.item', 'value')
});
```
- adding a collection item during `beforeBuild`, which can be used as an alternative to [Remote Collections](http://jigsaw.tighten.co/docs/collections-remote-collections/) as a way to dynamically create collection items, e.g.:
> _bootstrap.php_
```
$events->beforeBuild(function (Jigsaw $jigsaw) {
$jigsaw->setConfig('collections.posts', [
'extends' => '_layouts.master',
'items' => [
[
'content' => 'Content for post #1',
'filename' => 'post_1',
],
],
]);
});
```
---
Note that when creating a …
> Update `setConfig()` method in event listeners

- readme.md
The site appears to support HTTPS, but it doesn't redirect there. Lets link to the secure variant by default 🙂
> Use secure links in readme

- .gitignore
- composer.lock
based on getcomposer.org recommendation at https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control it is important to have `composer.lock` within git.
> Committing this file to VC is important because it will cause anyone who sets up the project to use the exact same versions of the dependencies that you are using. Your CI server, production machines, other developers in your team, everything and everyone runs on the same dependencies, which mitigates the potential for bugs affecting only some parts of the deployments. Even if you develop alone, in six months when reinstalling the project you can feel confident the dependencies installed are still working even if your dependencies released many new versions since then. (See note below about using …
> remove composer.lock from gitignore

- stubs/site/.gitignore
I'm submitting this PR because tightenco/jigsaw#215 seems to have been forgotten, the person who made it didn't reply to my comment, and I have different changes from that one.
___
- I tried to keep the simplicity of the file by not changing much of how it looks.
- I referenced [Laravel's current gitignore](https://github.com/laravel/laravel/blob/289b1457317a08813b8998a9a225535926bd90ee/.gitignore) and picked out the ones that can also apply to Jigsaw.
- I added the staging and production folders and compiled assets as optional ignores in comments
I'm not sure about the the staging and production folders being optional though, **I feel like they should be ignored by default**.
> Updated gitignore stub (different from PR 215)

- stubs/mix/package.json
- stubs/site/config.php
- stubs/site/config.production.php
This PR adds a `config.production.php` stub.
___
The default `config.php` file contains a `production` key but it is always set to `false`.
When the user runs `npm run production` the value of this key remains false (unless they remember to add the prod config file) which may lead to unexpected behavior when they use that config key in their code.
___
**Details of changes:**
- I added a new stub that contains `'production' => true,`
- In `config.php` I moved the `production` key to the top so that it lines up with the new stub
- Since the `local` script in `package.json` is aliased to `dev`, I aliased `production` to `prod` (exactly like Laravel's npm scripts)
> Added production config stub

- src/Console/ServeCommand.php
This PR is in response to issue #216 and adds a new optional --host option to the serve command, allowing users to specify the hostname or ip address to bind to.
> Added new host option to the serve command

- src/Console/BuildCommand.php
- tests/SnapshotTestCase.php
This commit resolves #276 by presenting the user with a confirmation prompt when the build destination is set to a custom path. A `--no-warnings` option can be passed to the command to bypass this check.
> Add confirmation for custom destination paths

- readme.md
Pre-1.0 upgrade page was [removed from tightenco/jigsaw-site](https://github.com/tightenco/jigsaw-site/commit/2942673693aacc7db115c4d17a334357cb728048).
Fixes #295.
> Remove old pre-1.0 upgrading instructions

- src/SiteBuilder.php
- tests/SnapshotTest.php
- tests/SnapshotTestCase.php
The SiteBulider and tests use:
Illuminate\Filesystem\Filesystem allFiles()
instead of:
TightenCo\Jigsaw\File\Filesystem files()
As the second param ($hidden = false) isn't set to true, dotfiles are not built.
Added a .DS_Store into the test source
Added two explicit tests
* check that dotfile is present
* check that .DS_Store file isn't present
> Build dotfiles

- src/PathResolvers/CollectionPathResolver.php
- tests/FilePathTest.php
This PR addresses https://github.com/tightenco/jigsaw/issues/344. 
Collection item filenames are first transliterated, and then sanitized to remove invalid characters; the second step maintained only letters from the Latin character set, which removed non-Latin (e.g. Korean) characters. Instead, the sanitization will now target common invalid characters explicitly for removal, and leave everything else.
> Allow international characters in collection file names

- src/File/Filesystem.php
- tests/EventsTest.php
Fixes #322.
The test would still work if `trimPath()` is used.
I just tried to test if `writeOutputFile` can handle a leading slash in `$file_path`.
> rightTrim Directory Path

- jigsaw-core.php
- src/File/ConfigFile.php
Closes #263
Copied from issue:
> ### Proposal
> 
> I suggest enabling Jigsaw to check if a `helpers.php` file exists in the project root.
> 
> If true, merge the arrays in `config.php` and `helpers.php`.
> 
> If false, nothing breaks (similar to how the `blade.php` file is optional).
> 
> ### Reason
> 
> Jigsaw's flexibility allows us to easily add any helper in the config file.
> 
> This is great, but generally a config file should consist of constant/static values. It would make sense to put helper functions in a separate file.
> 
> Users should have the option to use a separate file, but still be free to put everything in a single file if they prefer it that way.
Additional note:
I decided to add the code in `ConfigFile.php` because *although helpers is a separate file, it is …
> Allow merging optional helpers file to config file

- src/Collection/Collection.php
- src/Handlers/CollectionItemHandler.php
- tests/CollectionItemTest.php
This PR creates the base functionality to allow filtering collections. Filtering allows for specific features, like not publishing draft messages, to be implemented by other projects.
Related to #221
> Support filtering collections

- composer.json
- composer.lock
- src/Parsers/JigsawMarkdownParser.php
- tests/snapshots/escape-test-hybrid/index.html
- tests/snapshots/index_test_two/index.html
This PR rolls back the change to depending on beta versions of Parsedown and Parsedown-Extra from https://github.com/tightenco/jigsaw/pull/330 (which addressed https://github.com/tightenco/jigsaw/issues/318). The original motivation for the change was to fix a Parsedown but in the handling of single-line HTML markup (e.g. `<h1>Hey</h1><h2>There</h2>`), but a manual fix has been provided in `JigsawMarkdownParser` that obviates the need to switch Parsedown versions. That manual fix has been updated on this PR to support the earlier `1.7.*` and `0.7.*` versions.
Relying on the `beta` versions was preventing new installations using `composer require tightenco/jigsaw` from pulling the most recent version, since the newly-generated `composer.json` file that results from running `composer …
> Rollback Parsedown and Parsedown-Extra to stable versions

- src/Console/ServeCommand.php
This PR fixes a regression in the output printed to console when running the `serve` command with a non-default host. The command passed to PHP to serve does honor the `host` parameter correctly so this is just fix for the console output.
Current behavior:
```bash
$ ./vendor/bin/jigsaw serve --host 0.0.0.0
Server started on http://localhost:8000
```
Expected behavior:
```bash
$ ./vendor/bin/jigsaw serve --host 0.0.0.0
Server started on http://0.0.0.0:8000
```
It looks like this was a regression introduced when #266 was merged because the initial implementation of the `host` option (#230) had this code.
> Correctly print to console for serve command

- src/Collection/CollectionRemoteItem.php
- tests/RemoteCollectionsTest.php
This PR updates the CollectionRemoteItem class to process remote collection items as `.blade.md` instead of `.md`. 
Closes issue #362
> Update CollectionRemoteItem class to process files as blade.md

- composer.json
- composer.lock
This PR updates the `parsedown-extra` dependency version constraint to `^0.8`, to pick up [the fix that allows Parsedown Extra to work on PHP 7.4.](https://github.com/erusev/parsedown-extra/pull/135) 
https://github.com/tightenco/jigsaw/pull/398 is no longer needed. Thanks @josecanhelp for the insight!
> Update parsedown-extra dependency version to ^0.8

- src/SiteBuilder.php
Addresses https://github.com/tightenco/jigsaw/issues/413
When generating the array of links for all output files, `getOutputLink()` currently relies on the `$file->path()`, which may contain the directory separator `\` on Windows. This PR converts those to `/` to correctly generate a link, rather than a file path.
> Output links generated on Windows need $file->path() converted to `/`

- src/Jigsaw.php
- tests/JigsawMacroTest.php
Adding the macro trait to the Jigsaw class makes it much easier to extend and customize certain aspects of Jigsaw. For example,  I'm using my [Neocities Package](https://github.com/reed-jones/Neocities-php) which allows me to upload deploy the compiled files using the `afterBuild` event. Using the macro, I can abstract away the implementation and provide an installable plugin which can easily be used.
```php
Jigsaw::mixin(new NeocitiesJigsawDeployment);
$events->afterBuild(function (Jigsaw $jigsaw) {
if ($jigsaw->getEnvironment() === 'production') {
$jigsaw->deployToNeocities();
}
});
```
> added macro trait to Jigsaw class

- jigsaw
- jigsaw-core.php
- src/Jigsaw.php
- tests/CustomCommandTest.php
I'm not sure this is the best way to go about it, but I'm proposing to add the ability to create new commands under the jigsaw name. In a similar vein to my other PR (#408), however this customizes the CLI interface instead of just actions triggered on events. 
My use-case again is easier deployments.
```php
// bootstrap.php
$container->get(Jigsaw::class)->registerCommand(RunDeploymentCommand::class);
```
In my project, I extended the `BuildCommand`, renamed it to 'deploy', then after it completes the build process, I run my deploy.
```php
use TightenCo\Jigsaw\Console\BuildCommand;
class RunDeploymentCommand extends BuildCommand
{
private $jigsaw;
public function __construct($container)
{
parent::__construct($container);
$this->jigsaw = $container->get(Jigsaw::class);
}
protected function …
```
> added ability to customize commands

- composer.json
- composer.lock
- tests/DefaultScaffoldInstallerTest.php
This updates Illuminate dependencies to version 6.14, and is based on PR #392 from @bakerkretzmar. His original PR had gotten out of date after some more recent merges.
Thanks @bakerkretzmar!
> Update Illuminate dependencies to 6.x

- src/Handlers/CollectionItemHandler.php
Its typehinted as `Collection`, however in [jigsaw-core.php line 159](https://github.com/tightenco/jigsaw/blob/master/jigsaw-core.php#L159) an array is passed in (from `TightenCo\Jigsaw\File\ConfigFile` ).
> remove incorrect typehint from CollectionItemHandler

- jigsaw-core.php
- src/Parsers/JigsawMarkdownParser.php
- src/Parsers/MarkdownParser.php
- tests/snapshots/escape-test-hybrid/index.html
- tests/snapshots/escape-test-markdown/index.html
As referenced in https://github.com/tightenco/jigsaw/issues/424, the recent change in Markdown parsers from https://github.com/tightenco/jigsaw/pull/416 altered the default behavior for language class names applied to fenced code blocks. The previous parser (Parsedown) followed the Prism convention of prefixing language class names with `language-*`, whereas the new parser (PHP Markdown) omits the prefix.
This PR restores the previous Jigsaw behavior, to prevent breaking sites that relied on the `language-` prefix for syntax highlighting. 
In addition, since PHP Markdown exposes this setting (and others) through a series of configuration options, this PR makes those settings easily configurable in `bootstrap.php`. Specifically:
- it updates the MarkdownParser binding to use a singleton, …
> Restore "language-" prefix for fenced code blocks

- src/Handlers/MarkdownHandler.php
- src/Parsers/JigsawMarkdownParser.php
- tests/AtSymbolInMarkdownTest.php
This PR simplifies the escaping of the `@` symbol in markdown files, removing special cases that were intended to catch most occurrences but preserve `@` in the case of `mailto:` links. The recent switch of the markdown parser to use PHP Markdown library enables us to use a callback for formatting URLs, in which we can undo the Blade escaping that was added in `MarkdownHandler`.
> Improve Blade-Markdown `@` escaping

- src/File/CopyFile.php
- src/File/InputFile.php
- src/File/OutputFile.php
- src/Handlers/BladeHandler.php
- src/Handlers/CollectionItemHandler.php
- src/Handlers/DefaultHandler.php
- src/Handlers/MarkdownHandler.php
- src/Handlers/PaginatedPageHandler.php
- src/Jigsaw.php
- src/SiteBuilder.php
- tests/CollectionItemTest.php
- tests/SiteBuilderTest.php
This PR adds a `getSourceFileInfo()` method to the Jigsaw class, for reference during the `afterBuild` event. 
`getSourceFileInfo()` returns a collection of all output files that were generated. For each item:
- the key contains the path of the output file relative to the `build` directory (e.g. `/posts/my-first-post`)
- the value contains the Jigsaw `InputFile` object for the source file. On `InputFile`, every method from PHP's [SplFileInfo](https://www.php.net/manual/en/class.splfileinfo.php) class is available.
This is similar to `getOutputPaths()`, which returns just the output paths (i.e., the keys from `getSourceFileInfo()`).
> Expose source file info to afterBuild event

- stubs/site/config.php
- stubs/site/source/_layouts/master.blade.php
I'm reviving another old/dead PR tightenco/jigsaw#167 by someone else.
Keith seemed to be interested in merging it but the PR author never responded to the requested changes.
**Differences from the other PR**
- I didn't add keywords
- I didn't add the `language` key in the config. PHP null coalesce does an `isset()` behind the scenes which will return true even for `''`. `'language' => 'en',` is redundant and `'language' => '',` would cause unintended behavior.
- I added `<link rel="canonical" href="{{ $page->getUrl() }}">` and `<meta name="referrer" content="always">`
- I didn't add YAML front matter to `source/index.blade.php`
Additional note: I added the new config keys *before* `collections` because `title` and `description` are just one-line config keys while `collections` can …
> Added SEO tags to master.blade.php stub

- src/File/InputFile.php
- src/File/OutputFile.php
- src/Jigsaw.php
- src/SiteBuilder.php
- tests/SiteBuilderTest.php
This revises #429 
This PR changes the `getSourceFileInfo()` that was made accessible during the `afterBuild` event to `getPages()`. 
Now, instead of returning the `InputFile` as the value of each item in the collection, it returns the `PageData`, so it mimics what is available to the `$page` variable inside a template. 
This means that the `afterBuild` event now has access to any variables defined on a page (which addresses #337), as well as the [metadata helper functions](https://jigsaw.tighten.co/docs/page-metadata/) like `getPath()` and `getModifiedTime()` for each page.
> Return PageData in getPages() method during afterBuild event

- composer.json
- composer.lock
- jigsaw-core.php
- src/View/BladeCompiler.php
- src/View/ComponentTagCompiler.php
- tests/BladeComponentTest.php
- tests/TestCase.php
This PR updates Jigsaw's Illuminate dependencies to version 7 (along with Symfony components to version 5). It also adds support for Blade's new `<x-component>`-style components.
The new component implementation mirrors the [Laravel behavior](https://laravel.com/docs/7.x/blade#components), with two exceptions:
- views are auto-discovered from `source/_components` rather than from `resources/views/components`
- components are not auto-discovered from an `app/View/Components` directory
Class-based components can be registered using `$bladeCompiler->component()` as mentioned [in the docs](https://jigsaw.tighten.co/docs/content-blade/#extending-blade-with-custom-directives)
> Support version 7 Illuminate dependencies and x-style component tags

- src/Loaders/CollectionRemoteItemLoader.php
- tests/RemoteCollectionsTest.php
I use a number of remote collections and after builds (even successful builds), the `source` folder is filled with all the newly created empty `_collection_name` folders. Looks like cleanup routine clears the `_tmp` folders created, but not their empty parents.
Related to issue #289
> Remove empty temp remote collection folders after build

- src/Collection/Collection.php
- tests/CollectionItemTest.php
As with the `filter` config option, this pull request adds support for mapping over the items after filtering.
It would be done like this:
```php
return [
'collections' => [
'posts' => [
'map' => function ($post) {
return new Post($post);
}
],
]
]
```
The example above would let you map the collection to a data object for example, where you could place larger helper methods.
If not sure which way round makes more sense, whether the items should be mapped and then filtered, or filtered then mapped. Mapping after makes sense since it might be a longer mapping process / more resource consumption.
> Added support for mapping over collection inside of config

- src/Support/helpers.php
- tests/FilePathTest.php
- tests/HelpersTest.php
The leftTrimPath helper was errantly removing leading periods from
file/directory names for paths. This is illustrated by the `.well-known`
subdirectory (https://tools.ietf.org/html/rfc8615) used by certain
apps/services to validate site-wide metadata. Without this change
including a directory in the source directory named `.well-known` will
be built into `build/well-known` which will not work in the published
site.
> Allow leading periods in path names

- jigsaw-core.php
- src/Loaders/CollectionRemoteItemLoader.php
- tests/RemoteCollectionsTest.php
This PR passes the config array to a callback that is used in the `items` setting of a remote collection. 
It allows the `items` callback to reference other config variables, allowing an easier way to reference different API URLs, for example, in local and production environments. (Addresses #361)
> Allow access to config variables in remote collection callback

- src/Console/ServeCommand.php
As someone new to Jigsaw, it was a little weird to me that I had to first run `build` before I could run server. Most static site generators I've ran across run `build` as part of server. This merge request calls `build` by default when doing `serve` (passing in the environment). I've also included a `--no-build` option in `serve`.
> run build as part of the serve command

- src/Scaffold/ProcessRunner.php
> ./vendor/bin/jigsaw init docs
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in vendor/tightenco/jigsaw/src/Scaffold/ProcessRunner.php`
> use Process::fromShellCommandline instead of constructor

- src/Collection/CollectionItem.php
- tests/CollectionItemTest.php
This PR adds a static `forItem` method as a named constructor on CollectionItem, for use when instantiating decorated collection item classes while mapping (from #447). It correctly sets the `collection` variable on the new class, so collection-related methods (like `getNext()`, `getPrevious()`, etc.) will function correctly.
> Add `fromItem` named constructor to CollectionItem

- .env
- jigsaw-core.php
- tests/ConfigVariableTest.php
The latest upgrade to vlucas/phpdotenv 4.0 broke using .env files, because of a breaking change made from 3 -> 4: https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md#v3-to-v4
This fixes the issue and changes the test to use an actual .env file.
> Fix .env files due to breaking change on vlucas/phpdotenv 4.0

- composer.lock
- src/View/BladeCompiler.php
This PR fixes Jigsaw's `BladeCompiler` to correspond to [changes](https://github.com/laravel/framework/commit/3f537ca1c7cbf14af34dcf697801db75f2b173d3#diff-314543ef8cd684a5a1ca0d2388d419eb) in `Illuminate/View/Compilers/BladeCompiler` that were made in v7.9.
> Fix BladeCompiler to incorporate changes in Illuminate/View

- composer.lock
- src/View/BladeCompiler.php
This PR reverses the parameter order of the `compileComponentTags` instantiation in `BladeCompiler`, to pick up [another change](https://github.com/laravel/framework/commit/520544dc24772b421410a2528ba01fd47818eeea#diff-314543ef8cd684a5a1ca0d2388d419eb) made in Illuminate/View v7.9.2.
(Closes #462)
> Fix BladeCompiler to incorporate changes in Illuminate/View, again

- jigsaw-core.php
- src/Console/BuildCommand.php
- src/File/ConfigFile.php
- src/Handlers/CollectionItemHandler.php
- src/Loaders/DataLoader.php
- src/View/ViewRenderer.php
- tests/ViewRendererTest.php
I noticed the config was initially being created as an array in ConfigFile, however in some places it was being used as a Collection instead (the Constructor for CollectionRemoteItemLoader). I previously fixed a very similar bug https://github.com/tightenco/jigsaw/pull/423 and was tempted to remove the typehint again, but after a little digging I found what what happening.
in `BuildCommand`->`includeEnvironmentConfig` It actually overwrites the original array config with a new collection config. This fix just makes it a collection from the start, (and undoes my previous typehint removal)
> collect config during initial creation

- src/Handlers/PaginatedPageHandler.php
- tests/PaginationTest.php
This PR enables pagination for `.blade.md` template files; previously, `PaginatedPageHandler` limited pagination to only being used on `.blade.php` templates.
Addresses #474
> Enable pagination on .blade.md templates

- stubs/mix/package.json
Fixes #505 (1/2, see tighten/laravel-mix-jigsaw#17). Shouldn't break anything since this is only used for new installs.
~~The reason I went with `JIGSAW_ENV` instead of something like `--environment` or another new argument is so that this is treated as just a regular environment variable. [Laravel Mix v6 is also making this change](https://github.com/JeffreyWay/laravel-mix/commit/c29d2f92456d35b5f92e521f551e089c7f8c94f8), so I think it makes sense to stay consistent with them and aim for forwards-compatibility with other tools.~~
~~We could also just piggyback on `NODE_ENV`, which would mean using `development` instead of `local` here and in `laravel-mix-jigsaw`. Would that be confusing though?~~
We can change `'development'` to `'local'` internally in `laravel-mix-jigsaw`. I don't think …
> Update default build scripts to not pass --env

- readme.md
Adds badges for github workflow status, Packagist version, and downloads. 
**Rendered in phpstorm markdown preview**
> Add badges for build status, Packagist

- src/Support/helpers.php
- tests/HelpersTest.php
Adds a `url()` helper that just prepends the configured `baseUrl` value to whatever you pass it. This makes generating absolute URLs, which are pretty much required for some deployment environments like GitHub Pages, cleaner.
```html
<script src="{{ trim($page->baseUrl, '/') }}{{ mix('js/main.js', 'assets/build') }}" defer></script>
<a href="{{ trim($page->baseUrl, '/') }}/about-me">About Me</a>
<script src="{{ url(mix('js/main.js', 'assets/build')) }}" defer></script>
<a href="{{ url('about-me') }}">About Me</a>
```
See #515, https://github.com/tighten/jigsaw/issues/254#issuecomment-415583895, and https://github.com/tighten/jigsaw/issues/442#issuecomment-612903405.
> Add url() helper

- src/Loaders/CollectionDataLoader.php
- tests/RemoteCollectionsTest.php
This PR updates Jigsaw to silently ignore collection items without a matching handler, instead of throwing an exception.
Fixes #488, closes #494.
> Ignore collection items without a matching handler

- src/Console/BuildCommand.php
This PR adds the ability to disable pretty URL generation via the config file. Previously, the only to turn this off was by passing `--pretty=false` to the build command. Now you can also disable it by adding`'pretty' => false` to the top level of `config.php`.
Closes tighten/laravel-mix-jigsaw#18.
> Allow disabling pretty URLs via config file

- stubs/mix/package.json
- stubs/mix/tailwind.config.js
- stubs/mix/webpack.mix.js
- stubs/site/source/_assets/css/main.css
- stubs/site/source/_layouts/master.blade.php
- stubs/site/source/index.blade.php
This PR makes the necessary changes to include Tailwind CSS and PostCSS in the default installation instead of SCSS.
- Updated NPM dependencies
- Updated `webpack.mix.js` configuration
- Added `tailwind.config.js` with the `purge` option configured
- Added some very basic styles to the master layout and index page
> Use Tailwind CSS and PostCSS instead of SCSS in default installation

- src/View/ComponentTagCompiler.php
- tests/BladeComponentTest.php
Ahoy-hoy splendid people of Tighten thanks for Jigsaw it's rad-biscuits 💜
I'm rebuilding a static site (originally Gatsby) and have been finding the manual registration of class-based Blade components as discussed in feels #492 a bit of a fiddle / doesn't scale well. For context I'm using inline Blade class components pretty much exclusively (_love_ those inline class components 🙌).
This PR builds on #440 proposes a solution for autoloading based on a `Components` namespace being used. I have intentionally left adding this mapping to `composer.json` as a manual step. After looking at adding this programmatically via `init` I found ensuring correct integration with subclasses of `ScaffoldBuilder` inluding 3rd party presets started throwing up too many questions and my internal KISS 🚨 alarm …
> Support autoloading class components

- composer.json
- composer.lock
- tests/PhpOpenTagInMarkdownTest.php
- tests/SnapshotTestCase.php
- tests/TestCase.php
- It seems that testing for `php-7.2` version at least on GitHub action, and it should let this package require `php-7.2` version at least.
- Using the `php-7.2` version to upgrade the cached dependencies(`composer.lock`).
- According to the official [PHPUnit doc](https://phpunit.readthedocs.io/en/7.5/fixtures.html), it should be `protected function setUp(): void` and `protected function tearDown(): void` methods.
- Using the `PhpOpenTagInMarkdownTest` class name to be compatible with `PSR-4` autoloading.
> Improvements for PHPUnit assertion and fixtures

- src/Collection/CollectionRemoteItem.php
- tests/RemoteCollectionsTest.php
This PR updates handling of the temporary filename for a remote collection item, which was failing on PHP 8 when encountering a string key. If present, the string key will be used as the filename, rather than concatenating a numeric index to the collection name.
Addresses https://github.com/tighten/jigsaw/issues/524
> Use string key as remote collection item temporary filename, if present

- tests/IterableObjectTest.php
- Using the `assertInstanceOf` to assert expected class instance.
- Using the `assertInt` to assert expected type is `int`.
> Improve PHPUnit assertions

- src/SiteBuilder.php
- tests/PageDataBindingTest.php
This PR binds Jigsaw's page data into the container as `'pageData'` immediately before rendering each Blade template, making it possible to inject into components as described in https://github.com/tighten/jigsaw/issues/492#issuecomment-762669802:
```php
<?php
namespace Components;
use Illuminate\View\Component;
use Illuminate\Container\Container;
class Layout extends Component
{
public $page;
public function __construct()
{
$this->page = Container::getInstance()->make('pageData');
}
public function render()
{        
return Container::getInstance()->make('view')->make('_components.layout');
}
}
```
```blade
{{-- source/index.blade.php --}}
{{-- No longer necessary to pass $page in manually! --}}
<x-layout>
<div class="p-8">
<h1 class="text-3xl font-bold">Hello world!</h1>
</div> …
```
> Bind page data into container

- src/Scaffold/PresetPackage.php
Allow the use of versions and constraints when using jigsaw init command
If one would like to use theme-vendor/my-theme:dev-main
e.g. during theme development
it will end with a failure
In Finder.php line 591:
The "/path/to/jigsaw_site/vendor/theme-vendor/my-theme:dev-main" directory does not exist.
The path comes from PresetPackage->name
Solution:
split up PresetPackage->name in PresetPackage->name and PresetPackage->constraint and concatenate them where needed.
Because the PresetPackage expected the name to be without a constraint (:xy) until now, this should not be breaking anything.
> Allow the use of versions and constraints when using jigsaw init command

- src/Handlers/PaginatedPageHandler.php
- tests/PaginationTest.php
Currently, you can set the `perPage` setting either in your template file or as a global setting in config.php. This pull request would allow you to set the `perPage` setting for a specific collection in config.php. The order of preference would be as follows:
1. Within template
2. Collection specific in config.php
3. Global in config.php
4. Default of 10
Note that I don't really love how this looks in the code itself, but it's better than keeping it all on the same line together. One alternative would be a temporary variable, which I don't love either. I'm open to other implementation suggestions.
> Allow Collection Specific perPage Setting

- jigsaw-core.php
- src/Console/BuildCommand.php
- tests/TestCase.php
- tests/ViewPathTest.php
This PR allows users to configure the location of the Blade view path. This facilitates, for example, storing Blade views somewhere other than `source/`. Defaults to `source/` so should be entirely backwards compatible.
> Allow configuration of Blade view path

- src/View/ComponentTagCompiler.php
Thanks Tighten team for this static site generator.
Following the latest additions for Blade components support I want to propose a change in the anonymous vs class based component precedence giving precedence to class based ones. 
Assuming a Blade template for the component is defined in `_components`, e.g. `_components/image.blade.php`, and the corresponding Component class defined, e.g. `Image extends Component` under the `Components` namespace, inverting the evaluation criteria for class based components with anonymous components allows to add methods and additional attributes to the component that otherwise would be ignored.
This probably covers my specific case in which I need to define an image component whose Blade file is located under `_components/image.blade.php` and whose …
> Give precedence to class based component

- src/Events/EventBus.php
- tests/EventsTest.php
Hi, 
There is a slight issue with the `EventBus`. When you add a listener to the event collection, it creates a new collection by merging with a `collect($arguments[0])` call. This has some unforeseen side effects when you use an invokable event listener with an internal object.
```php
$events->afterCollections(new class {
private $object;
public function __construct()
{
$this->object = (object) [];
}
public function __invoke(Jigsaw $jigsaw) {
dump($jigsaw);
}
});
```
This example will currently throw an error:
```bash
PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::handle() in /Users/doekenorg/code/doekenorg/vendor/tightenco/jigsaw/src/Events/EventBus.php:33
```
This update will fix that problem, by just appending the first argument to the collection that already …
> Allow invokeable event listeners

- .github/workflows/main.yml
- composer.json
- src/Console/BuildCommand.php
- src/IterableObject.php
- src/Support/helpers.php
- tests/config.php
Adds support for PHP 8.1:
- Bump minimum versions of some dependencies.
- Default some arguments to an empty string where passing `null` is deprecated.
- Override the base Collection `except` method to handle null being passed in.
- Override the base Collection `has` method to use `array_key_exists` instead of `offsetExists` (may not be absolutely necessary but maintains consistency with Illuminate 7 bevahiour, see #571).
Also:
- Add test matrix runs on PHP 8.1 and with minimum possible dependency versions.
- Explicitly drop support for PHP 7.2 (Illuminate 8 requires `^7.3`). This isn't a breaking change, right? People who absolutely need to stay on PHP 7.2 just can't upgrade?
Closes #601.
> Add support for PHP 8.1

- src/Events/EventBus.php
I was recently adding some event listeners to a Jigsaw site and noticed that PHPStan complains that these methods don't exist on the `EventBus` instance. 👍🏻
I also added the `Collection` type to the 3 properties as they are always that type (but I'm happy to remove that).
> feat: add event bus type hints

- src/Console/ServeCommand.php
This allows us to call `jigsaw serve` command with `-q` or `-vv` options and it will work just like `jigsaw build` command. 👍
Currently if you use a custom build path and run `jigsaw serve -q` it does not ask for a confirmation nor continue - it's kinda broken. 😄
> Improve serve command option handling

- src/Events/EventBus.php
Reverts part of #635 to remove typed properties, which are only supported on PHP 7.4+. Not sure how the tests passed there initially.
> Fix backwards compatibility break with PHP 7.3

- src/Handlers/CollectionItemHandler.php
- tests/SnapshotsTest.php
- tests/snapshots/blade-no-extends/config.php
- tests/snapshots/blade-no-extends/source/_layouts/main.blade.php
- tests/snapshots/blade-no-extends/source/_pages/page-a-markdown.md
- tests/snapshots/blade-no-extends/source/_pages/page-b-nothing.blade.php
- tests/snapshots/blade-no-extends/source/_pages/page-c-empty.blade.php
- tests/snapshots/blade-no-extends/source/_pages/page-d-extends.blade.php
- tests/snapshots/blade-no-extends/source/index.blade.php
- tests/snapshots/blade-no-extends_snapshot/index.html
- tests/snapshots/blade-no-extends_snapshot/pages/page-a-markdown/index.html
- tests/snapshots/blade-no-extends_snapshot/pages/page-d-extends/index.html
Blade files that don't extend a parent template should never be rendered. In some cases we were rendering them anyway, and because they don't have a template or path, their output path defaulted to `''`, overwriting the root `index.html` page or creating a root `.html` page.
This PR ensures that we don't create an `OutputFile` for files we don't want to render.
Closes #670.
> Fix Blade files without `extends` overwriting other pages

- composer.json
- src/Console/InitCommand.php
- src/Loaders/CollectionDataLoader.php
- src/Parsers/CommonMarkParser.php
- src/Parsers/JigsawMarkdownParser.php
- src/Parsers/MarkdownParser.php
- src/Parsers/MarkdownParserContract.php
- src/PathResolvers/CollectionPathResolver.php
- src/Providers/MarkdownServiceProvider.php
- tests/CommonMarkTest.php
Adds the option to use `league/commonmark` to parse and render markdown. This can be enabled by setting the `commonmark` config to any value. To configure the CommonMark environment or add extensions, the `commonmark` config can be set to an array with `config` and `extensions` keys:
```php
// config.php
return [
'commonmark' => [
'config' => ['enable_em' => false],
'extensions' => [new AttributesExtension],
],
];
```
The default configuration includes 4 extensions: attributes, smart punctuation, strikethrough, and tables. Extensions can easily be added or removed by overriding the `commonmark.extensions` config key.
Two other things:
- I'm not sure `MarkdownParserContract` is strictly necessary, and I wouldn't mind getting rid of it if we can, I just needed something to bind to.
- …
> Add CommonMark markdown rendering option

- src/Container.php
- src/File/ConfigFile.php
- tests/RemoteCollectionsTest.php
- tests/TestCase.php
This PR addresses the issue https://github.com/tighten/jigsaw/issues/572
It allows us to set the collection using a function.
It means that now it is possible to get the collections and entries from an external API dynamically without having to expressly set the collections.
> Allow setting collections using a function

- .github/workflows/test.yml
- .php-cs-fixer.php
- composer.json
- src/Scaffold/InstallerCommandException.php
- src/Support/ServiceProvider.php
- tests/BladeComponentTest.php
- tests/CollectionItemTest.php
- tests/CustomCommandTest.php
- tests/CustomScaffoldInstallerTest.php
- tests/DefaultScaffoldInstallerTest.php
- tests/EventsTest.php
- tests/FilesystemTest.php
- tests/Haiku.php
- tests/InitCommandTest.php
- tests/IterableObjectTest.php
- tests/PageDataBindingTest.php
- tests/PaginationTest.php
- tests/PresetScaffoldBuilderTest.php
- tests/RemoteCollectionsTest.php
- tests/ScaffoldTest.php
- tests/SiteBuilderTest.php
- tests/TestCase.php
- tests/TestCaseTest.php
- tests/ViewPathTest.php
- tests/fixtures/tmp/.gitignore
This PR updates all tests to use the real filesystem instead of a virtual one, and uninstalls `mikey179/vfsstream`. This brings the test environment/behaviour closer to how Jigsaw actually runs in real environments, and it makes debugging and inspecting failing tests significantly easier.
Kind of similarly to Laravel's `Storage::fake()` (which only cleans up previous tests' files at the beginning of the next test run), this PR only cleans up test files if all tests passed, so if anything goes wrong the test files are preserved and we can review them.
I also added some cleaner setup helper methods, but to keep this PR from getting too noisy I didn't replace the old ones everywhere yet.
The performance hit here (I _think_ using the real filesystem is slower) is negligible.
> Use real filesystem in tests

- src/Parsers/CommonMarkParser.php
Allows renderers to be defined in the `config.php` file, which are then passed to the `league/commonmark` package.
This means packages like [spatie/commonmark-highlighter](https://github.com/spatie/commonmark-highlighter) can be used.
```php
// config.php Example
<?php
return [
'production' => false,
'baseUrl' => '',
'title' => 'Jigsaw',
'description' => 'Website description.',
'collections' => [],
'commonmark' => [
'renderers' => [
\League\CommonMark\Extension\CommonMark\Node\Block\FencedCode::class => new \Spatie\CommonMarkHighlighter\FencedCodeRenderer,
\League\CommonMark\Extension\CommonMark\Node\Block\IndentedCode::class => new \Spatie\CommonMarkHighlighter\IndentedCodeRenderer,
],
],
];
```
> CommonMark Renderer

- .github/workflows/format.yml
Addresses an issue with the `format.yml` GitHub Action workflow where it fails for pull requests from forked repositories. It adds the `repository` parameter, ensuring the correct branch from the fork is checked out.
Without this PRs fail checks with: A branch or tag with the name 'xyz-etc' could not be found
> Fix Format Action for Forked Repos

- src/Providers/ViewServiceProvider.php
- src/View/DynamicComponent.php
- tests/snapshots/dynamic-component/source/_components/alert.blade.php
- tests/snapshots/dynamic-component/source/index.blade.php
- tests/snapshots/dynamic-component_snapshot/index.html
Fixes `<x-dynamic-component>` Blade components, which don't work but should have been supported (and might have worked at some point in the past).
All this does is override the `DynamicComponent` component class so that it uses Jigsaw's customized `ComponentTagCompiler` instead of Laravel's. I didn't even change anything in `DynamicComponent`, just the fact that we redeclare it picks up the new compiler because of the namespace it's in.
There might be more nuance to explore here, this is super basic and just makes the happy path example in the included snapshot test work as expected.
Closes #707.
> Fix dynamic components

- .gitattributes
This prevents unnecessary files being distributed to vendor installs. This will save about 100K on each install, which isn't much but it also means that these don't show up in IDE suggestions.
> chore: add new files to `.gitattributes`

- composer.json
It looks like this update was missed as part of #724, which prevents Laravel 12 from being actually used.
> chore(deps): add support for `illuminate/collections:^12`

- stubs/site/package-lock.json
- stubs/site/package.json
This PR bumps the version of the Vite plugin to include a [recently merged bug fix](https://github.com/tighten/jigsaw-vite-plugin/pull/1).
> Update Vite plugin version
