tighten/jigsaw

jigsaw, src/Console/BuildCommand.php, src/Console/Command.php, src/Console/InitCommand.php, src/Filesystem.php, src/Handlers/DefaultHandler.php, src/Jigsaw.php
=> Extend Filesystem to include hidden files when fetching all files

src/File/TemporaryFilesystem.php
quickRandom is deprecated in 5.3
=> Replace deprecated quickRandom() with random()

src/Collection/Collection.php, src/CollectionDataLoader.php, src/IterableObject.php, src/PathResolvers/CollectionPathResolver.php, src/PathResolvers/PrettyOutputPathResolver.php
=> Enforce SPR-2 syntax.

src/Collection/CollectionItem.php, src/CollectionDataLoader.php, src/IterableObjectWithDefault.php, src/PageData.php, src/SiteBuilder.php, src/SiteData.php
=> Remove unused imports.

src/File/InputFile.php
The problem comes from windows paths using the `\` rather than `/`
Altered topLevelDirectory and relativePath to handle both `\` or `/`
=> The actual fix for collections on windows system

src/File/InputFile.php
Bring new `trimPath` helper in to replace `trim` for `relativePath()` method of `InputFile`
=> Bring new trimPath helper in to InputFile

composer.json, src/View/BladeMarkdownEngine.php, src/View/MarkdownEngine.php
Fixes https://github.com/tightenco/jigsaw/issues/142
=> Fix https://github.com/tightenco/jigsaw/issues/142

stubs/mix/package.json
Use local webpack rather than global.
Fix NODE_ENV variables so assets get optimized properly during production builds.
=> Fix package.json for mix scaffold

jigsaw-core.php, src/Support/helpers.php
Use configured build source in `public_path` helper instead of hardcoded `'source'` string.
=> Fix for public_path helper

.gitignore, jigsaw-core.php, src/View/ViewRenderer.php, tests/ViewRendererTest.php, tests/config.php
Reference: https://github.com/tightenco/jigsaw/issues/370
=> Adding view hint paths config option.

src/Collection/Collection.php, src/Collection/CollectionItem.php, src/Console/BuildCommand.php, src/Console/ServeCommand.php, src/Handlers/CollectionItemHandler.php, src/Handlers/PaginatedPageHandler.php, src/Jigsaw.php, src/Loaders/CollectionDataLoader.php, src/Loaders/DataLoader.php, src/PageData.php, src/PageVariable.php, src/PathResolvers/CollectionPathResolver.php, src/Scaffold/BasicScaffoldBuilder.php, src/Scaffold/PresetScaffoldBuilder.php, src/Scaffold/ScaffoldBuilder.php, src/SiteBuilder.php, src/SiteData.php
As promised in #417. This PR simply adds some type-hints to some constructors and methods where it isn't immediately clear what the parameters contain.
=> Added type-hints to various methods and constructors

stubs/site/.gitignore
**EDIT:**
I saw the performance PR and added another commit to avoid conflicts with it. (`_tmp` > `cache`)
___
Original comment:
Just added the `_tmp` folder that won't go away sometimes when the build fails.
Added an optional ignore.
=> Update gitignore stub again

stubs/site/.gitignore
I'm getting back into Jigsaw, updating my old projects.
While doing so, I noticed the mess I made in an old PR and decided to simplify them.
=> Minor change to gitignore stub (fixing my old PR)

tests/FilesystemTest.php, tests/PresetScaffoldBuilderTest.php, tests/SnapshotTest.php, tests/TestCase.php
This PR improves the compatibility with Windows.
Not really sure if commit 9c21733 is the best solutions.
=> Windows compatibility

.editorconfig, .gitattributes, contributing.md
Adds standard `.gitattributes`, `.editorconfig`, and `contributing.md` files.
=> Add base files

composer.json, jigsaw-core.php, src/Events/FakeDispatcher.php, src/IterableObject.php, src/View/BladeCompiler.php, src/View/ComponentTagCompiler.php, tests/BladeComponentTest.php
Does what it says on the box 😄 
@damiani I'm not positive that this won't break anything in any existing sites... thoughts? Might not be a huge deal to leave it until v2.
=> Update Illuminate components to v8

phpunit.xml, src/Collection/Collection.php
=> Fix PHP 8.1 deprecation notice

stubs/site/package.json
=> Update `larave-mix-jigsaw` in stub

stubs/site/package.json, stubs/site/source/assets/build/css/main.css, stubs/site/source/assets/build/js/main.js, stubs/site/source/assets/build/mix-manifest.json, stubs/site/tailwind.config.js
=> Upgrade tailwindcss to v3

src/Support/helpers.php, tests/CommonMarkTest.php, tests/HelpersTest.php
=> Fix `resolvePath()` removing directories called `0`

src/SiteBuilder.php
Fix for: https://github.com/tighten/jigsaw/issues/737
=> Fix: Mixed path delimiters on Windows (Fixes #737)

.gitignore, CONTRIBUTING.md
Updating the link to phpcs package and adding instructions on how to run the linting tools
=> Miscellaneous documentation updates
